# Site
name: "thespartoos"
title: "Alejandro Ruiz"
description: "Blog de Ciberseguridad"
logo: 'assets/images/thespartoos.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: alejandrorm689@gmail.com

# Authors
authors:
  thespartoos:
    name: thespartoos
    display_name: Thespartoos
    avatar: 'assets/images/thespartoos.png'
    web: https://thespartoos.github.io
    twitter: https://twitter.com/thespartoos
    description: "Creador del Blog de Ciberseguridad"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
kramdown:
   input: GFM
   syntax_highlighter_opts:
      disable : true
highlighter: rouge

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
